export const CATEGORIES = [
  {
    id: 'home-help', icon: '🏠', label: 'Home Help',
    tagline: 'Cleaners, Cooks, Nannies & More', count: 3200,
    subs: [
      { name: 'House Cleaner', icon: '🧹', from: 299, unit: 'visit' },
      { name: 'Cook / Chef', icon: '👨‍🍳', from: 399, unit: 'day' },
      { name: 'Nanny / Baby Care', icon: '🍼', from: 499, unit: 'day' },
      { name: 'Elder Caretaker', icon: '🧑‍⚕️', from: 449, unit: 'day' },
      { name: 'Gardener', icon: '🌿', from: 249, unit: 'visit' },
      { name: 'General Helper', icon: '🙋', from: 199, unit: 'task' },
    ],
  },
  {
    id: 'pick-drop', icon: '🛵', label: 'Pick & Drop',
    tagline: 'Groceries, Medicines, Parcels', count: 1800,
    subs: [
      { name: 'Grocery Run', icon: '🛒', from: 49, unit: 'trip' },
      { name: 'Medicine Pickup', icon: '💊', from: 39, unit: 'trip' },
      { name: 'Parcel Delivery', icon: '📦', from: 59, unit: 'trip' },
      { name: 'Document Courier', icon: '📄', from: 49, unit: 'trip' },
      { name: 'Buy From Shop', icon: '🏪', from: 69, unit: 'trip' },
      { name: 'Tiffin Pickup', icon: '🍱', from: 39, unit: 'trip' },
    ],
  },
  {
    id: 'repair', icon: '🔧', label: 'Repair & Tech',
    tagline: 'Mobile, Laptop, Appliance Repair', count: 2100,
    subs: [
      { name: 'Mobile Repair', icon: '📱', from: 199, unit: 'job' },
      { name: 'Laptop / PC Repair', icon: '💻', from: 349, unit: 'job' },
      { name: 'Appliance Repair', icon: '🔌', from: 299, unit: 'job' },
      { name: 'AC Service', icon: '❄️', from: 399, unit: 'job' },
      { name: 'TV Repair', icon: '📺', from: 249, unit: 'job' },
      { name: 'CCTV / Security', icon: '📷', from: 499, unit: 'job' },
    ],
  },
  {
    id: 'home-repair', icon: '🏗️', label: 'Home Repair',
    tagline: 'Plumbers, Electricians, Carpenters', count: 2800,
    subs: [
      { name: 'Electrician', icon: '⚡', from: 299, unit: 'day' },
      { name: 'Plumber', icon: '🚿', from: 349, unit: 'day' },
      { name: 'Carpenter', icon: '🪵', from: 399, unit: 'day' },
      { name: 'Painter', icon: '🎨', from: 349, unit: 'day' },
      { name: 'Mason / Tile Fixer', icon: '🧱', from: 399, unit: 'day' },
      { name: 'Welder', icon: '🔩', from: 449, unit: 'day' },
    ],
  },
  {
    id: 'it-services', icon: '💻', label: 'IT Services',
    tagline: 'Networking, POS, Smart Home Setup', count: 560,
    subs: [
      { name: 'Network Setup', icon: '📡', from: 499, unit: 'job' },
      { name: 'POS Technician', icon: '🖥️', from: 599, unit: 'job' },
      { name: 'Printer Repair', icon: '🖨️', from: 299, unit: 'job' },
      { name: 'Smart Home Setup', icon: '🏡', from: 699, unit: 'job' },
      { name: 'Server / IT Support', icon: '🗄️', from: 799, unit: 'day' },
      { name: 'CCTV / IP Camera', icon: '🔐', from: 549, unit: 'job' },
    ],
  },
  {
    id: 'manpower', icon: '👷', label: 'Manpower Supply',
    tagline: 'Labour Teams for Any Scale', count: 5000,
    subs: [
      { name: 'Construction Labour', icon: '🏗️', from: 700, unit: 'day' },
      { name: 'Factory Worker', icon: '🏭', from: 650, unit: 'day' },
      { name: 'Warehouse Helper', icon: '📦', from: 600, unit: 'day' },
      { name: 'Event Staff', icon: '🎪', from: 550, unit: 'day' },
      { name: 'Loading / Shifting', icon: '🚚', from: 600, unit: 'day' },
      { name: 'Cleaning Team', icon: '🧽', from: 500, unit: 'day' },
    ],
  },
  {
    id: 'shop-office', icon: '🏪', label: 'Shop & Office',
    tagline: 'Cashiers, Sales Staff, Office Boys', count: 1900,
    subs: [
      { name: 'Cashier', icon: '💰', from: 550, unit: 'day' },
      { name: 'Sales Boy / Girl', icon: '🛍️', from: 500, unit: 'day' },
      { name: 'Shop Helper', icon: '🤝', from: 450, unit: 'day' },
      { name: 'Office Boy', icon: '🗂️', from: 450, unit: 'day' },
      { name: 'Receptionist', icon: '🧑‍💼', from: 650, unit: 'day' },
      { name: 'Data Entry Operator', icon: '⌨️', from: 700, unit: 'day' },
    ],
  },
  {
    id: 'gig-jobs', icon: '💼', label: 'Gig Jobs',
    tagline: 'Part-time, Daily Wage, Contract', count: 4200,
    subs: [
      { name: 'Part-Time Jobs', icon: '⏰', from: 300, unit: 'day' },
      { name: 'Daily Wage Jobs', icon: '📅', from: 500, unit: 'day' },
      { name: 'Contract Jobs', icon: '📝', from: 18000, unit: 'mo' },
      { name: 'Full-Time Placement', icon: '🏢', from: 12000, unit: 'mo' },
      { name: 'Freelance Task', icon: '🎯', from: 200, unit: 'task' },
      { name: 'Internship', icon: '🎓', from: 8000, unit: 'mo' },
    ],
  },
];

export const TEAM_SIZES = [
  { count: 1,   label: '1 Worker',   badge: 'Solo',       multiplier: 1,    cls: 'bg-green-100 text-green-700' },
  { count: 5,   label: '5 Workers',  badge: 'Small Team', multiplier: 4.5,  cls: 'bg-green-200 text-green-800' },
  { count: 10,  label: '10 Workers', badge: 'Medium',     multiplier: 8.5,  cls: 'bg-green-300 text-green-900' },
  { count: 20,  label: '20 Workers', badge: 'Large',      multiplier: 16,   cls: 'bg-green-400 text-white' },
  { count: 50,  label: '50 Workers', badge: 'Bulk',       multiplier: 38,   cls: 'bg-green-600 text-white' },
  { count: 999, label: 'Full Team',  badge: 'Enterprise', multiplier: null, cls: 'bg-green-800 text-white' },
];

export const WORK_TYPES = [
  { id: 'construction', icon: '🏗️', label: 'Construction',   desc: 'Civil, masonry, RCC, shuttering' },
  { id: 'shifting',     icon: '📦', label: 'Shifting',        desc: 'Office & home relocation' },
  { id: 'events',       icon: '🎪', label: 'Events',          desc: 'Setup, ops, security & cleanup' },
  { id: 'factory',      icon: '🏭', label: 'Factory',         desc: 'Production, assembly, packing' },
  { id: 'warehouse',    icon: '🏢', label: 'Warehouse',       desc: 'Inventory, loading, dispatch' },
  { id: 'retail',       icon: '🛒', label: 'Retail / Season', desc: 'Festive & seasonal staff surge' },
];

export const BOOKING_TYPES = [
  { id: 'daily',    icon: '📅', label: 'Daily Wage',    desc: 'Pay per day worked' },
  { id: 'hourly',   icon: '⏱️', label: 'Hourly Labour', desc: 'Flexible hour billing' },
  { id: 'contract', icon: '📝', label: 'Contract',      desc: 'Fixed monthly terms' },
  { id: 'team',     icon: '👥', label: 'Team Project',  desc: 'Fixed-price project hire' },
];

export const TRUST = [
  { icon: '🛡️', title: 'ID Verified',     desc: 'Aadhaar, PAN & photo ID checked for every worker' },
  { icon: '🧪', title: 'Skill Tested',     desc: 'Practical trade tests before any worker goes live' },
  { icon: '🔍', title: 'Background Check', desc: 'Criminal & address verified via govt database' },
  { icon: '⭐', title: '2-Way Ratings',    desc: 'Transparent reviews with dispute resolution' },
  { icon: '💰', title: 'Escrow Payment',   desc: 'Funds released only after job completion sign-off' },
  { icon: '📍', title: 'Live Tracking',    desc: 'Real-time worker GPS & check-in/check-out logs' },
  { icon: '🏥', title: '₹5L Insurance',   desc: 'Accident cover on every booked job, zero premium' },
  { icon: '📞', title: '24/7 Support',     desc: 'Dedicated helpline for workers and clients always' },
];

export const STATS = [
  { value: '48,000+', label: 'Verified Workers' },
  { value: '1.2M+',   label: 'Jobs Completed' },
  { value: '98.4%',   label: 'Satisfaction Rate' },
  { value: '340+',    label: 'Cities Covered' },
];

export const PRICING = [
  { icon: '📅', tier: 'Daily Wage',    range: '₹500 – ₹1,500',        best: 'Home repair, site work' },
  { icon: '⏱️', tier: 'Hourly Labour', range: '₹80 – ₹250/hr',        best: 'Shops, events, delivery' },
  { icon: '📝', tier: 'Contract',      range: '₹18,000 – ₹60,000/mo', best: 'IT roles, supervisors' },
  { icon: '👥', tier: 'Team Manpower', range: '₹12,000 – ₹2,50,000',  best: 'Events, factories, shifting' },
];

export const DEMO_WORKERS = [
  { id: 1,  name: 'Rajan Thakur',  role: 'Master Electrician',     rating: 4.9, jobs: 312, exp: '8 yrs',  price: '₹850/day',   badge: 'Top Rated', verified: true, initials: 'RT', cat: 'home-repair' },
  { id: 2,  name: 'Suresh Kumar',  role: 'Plumber & Pipe Fitter',  rating: 4.7, jobs: 198, exp: '6 yrs',  price: '₹750/day',   badge: 'Pro',        verified: true, initials: 'SK', cat: 'home-repair' },
  { id: 3,  name: 'Amir Khan',     role: 'CCTV & Security Tech',   rating: 4.8, jobs: 245, exp: '5 yrs',  price: '₹1,100/day', badge: 'Top Rated',  verified: true, initials: 'AK', cat: 'it-services' },
  { id: 4,  name: 'Priya Sharma',  role: 'IT Support & Networking',rating: 4.9, jobs: 87,  exp: '3 yrs',  price: '₹1,400/day', badge: 'Rising ⭐',  verified: true, initials: 'PS', cat: 'it-services' },
  { id: 5,  name: 'Ramesh Verma',  role: 'AC Mechanic / HVAC',     rating: 4.6, jobs: 421, exp: '10 yrs', price: '₹950/day',   badge: 'Expert',     verified: true, initials: 'RV', cat: 'repair' },
  { id: 6,  name: 'Deepa Nair',    role: 'Home Cook & Chef',       rating: 4.8, jobs: 134, exp: '4 yrs',  price: '₹400/day',   badge: 'Pro',        verified: true, initials: 'DN', cat: 'home-help' },
  { id: 7,  name: 'Dev Raj',       role: 'Construction Supervisor',rating: 4.8, jobs: 156, exp: '12 yrs', price: '₹1,200/day', badge: 'Pro',        verified: true, initials: 'DR', cat: 'manpower' },
  { id: 8,  name: 'Kavita Singh',  role: 'House Cleaner & Helper', rating: 4.7, jobs: 289, exp: '5 yrs',  price: '₹300/visit', badge: 'Top Rated',  verified: true, initials: 'KS', cat: 'home-help' },
  { id: 9,  name: 'Mohan Das',     role: 'Carpenter & Furniture',  rating: 4.6, jobs: 201, exp: '9 yrs',  price: '₹600/day',   badge: 'Pro',        verified: true, initials: 'MD', cat: 'home-repair' },
];

// Language translations
export const LANG: Record<string, any> = {
  en: {
    toggle: 'हिंदी',
    nav: {
      home: 'Home', services: 'Services', pickDrop: 'Pick & Drop',
      manpower: 'Manpower', gigs: 'Find Jobs', workers: 'Workers',
      joinWorker: 'Join as Worker', postJob: 'Post a Job',
      profile: 'My Profile', dashboard: 'Dashboard', logout: 'Logout', login: 'Login',
    },
    home: {
      badge: "INDIA'S LARGEST LABOUR MARKETPLACE",
      h1a: 'Hire Verified Workers.',
      h1b: 'Find Jobs. Build Teams.',
      sub: 'From a single house cleaner to a 50-person construction team — book skilled, background-verified workers for every need, on demand.',
      hireBtn: 'Hire a Worker →',
      manpowerBtn: 'Book Manpower Team',
      jobBtn: 'Find a Job',
      searchPh: 'Search workers, services, or jobs...',
      categoriesTitle: 'All Service Categories',
      categoriesSub: '8 major categories · 48 sub-services · 48,000+ verified workers',
      viewAll: 'View All',
      pickDropTitle: '🛵 Pick & Drop Runner',
      pickDropSub: 'Send a nearby runner to buy groceries, pick up medicines, deliver parcels, or get anything from any shop — all within your neighbourhood.',
      sendRunner: 'Send a Runner →',
      workersTitle: 'Top Rated Workers',
      workersSub: 'Individually verified, skill-tested, and insured',
      browseAll: 'Browse All',
      trustTitle: 'Built on Trust & Safety',
      trustSub: 'Every worker on UrbanServe is verified, tested, and insured',
      manpowerCTATitle: 'Need a Full Labour Team?',
      manpowerCTASub: 'Select from 1 to 50+ workers for construction, events, factory ops, and relocation. Team deployed in under 4 hours.',
      buildTeam: 'Build Your Team →',
      pricingTitle: 'Transparent Pricing',
      pricingSub: 'No hidden charges. Platform fee of 12–18% on all bookings.',
      gigTitle: 'Looking for Work?',
      gigSub: 'Find part-time, daily wage, hourly, contract, or full-time jobs across IT, construction, shops, offices, and factories.',
      browseJobs: 'Browse All Jobs →',
      registerWorker: 'Register as Worker',
      aiTitle: 'AI-Powered Smart Matching',
      aiSub: 'Our AI engine analyses your job requirements, location, budget, and past ratings to instantly match you with the 3 best-fit verified workers.',
      aiBtn: 'Try AI Match →',
    },
    gigs: {
      title: '💼 Gig Job Marketplace',
      sub: 'Daily wage, hourly, part-time, contract & full-time opportunities',
      allCats: 'All Categories',
      allTypes: 'All Types',
      apply: 'Apply →',
      urgent: '🔴 Urgent',
      noJobs: 'No jobs match this filter.',
      postBtn: 'Post a Job',
      postTitle: 'Post a New Job Vacancy',
      jobTitle: 'Job Title',
      company: 'Company / Name',
      jobType: 'Job Type',
      pay: 'Pay / Salary',
      location: 'Location / City',
      skills: 'Required Skills (comma separated)',
      category: 'Category',
      markUrgent: 'Mark as Urgent',
      postSubmit: 'Post Job Live →',
      cancel: 'Cancel',
      workerCTATitle: 'Are You a Skilled Worker?',
      workerCTASub: 'Join 48,000+ verified workers earning on UrbanServe. Daily payouts, job guarantees, and accident insurance on every booking.',
      joinBtn: 'Join as a Worker — Free →',
      liveTag: '🟢 Live Jobs',
    },
    dashboard: {
      title: 'My Dashboard',
      welcome: (n: string) => `Welcome, ${n} 👋`,
      subtitle: 'Your profile at a glance',
      editProfile: 'Edit Profile',
      saveProfile: 'Save Changes',
      cancel: 'Cancel',
      logout: 'Logout',
      labels: {
        name: 'Full Name', email: 'Email', dob: 'Date of Birth',
        contact: 'Contact', skills: 'Skills', interests: 'Interests',
        location: 'Location', aadhaar: 'Aadhaar Card',
        verified: 'Verified', member: 'Member Since', role: 'Account Type',
      },
      noAadhaar: 'Not uploaded',
      viewAadhaar: 'View Aadhaar',
      myJobs: 'My Job Applications',
      noApps: 'No applications yet.',
      status: { pending: 'Pending', accepted: 'Accepted', rejected: 'Rejected' },
    },
    onboarding: {
      title: "Let's set up your profile",
      sub: 'Takes 2 minutes. You can edit anytime.',
      step: (c: number, t: number) => `Step ${c} of ${t}`,
      back: 'Back', next: 'Next', submit: 'Submit', saving: 'Saving…',
      skip: 'Skip for now',
      qs: [
        { q: "What's your full name?",           ph: 'Enter your full name',      type: 'text'      },
        { q: 'Your date of birth?',              ph: 'Select date of birth',      type: 'date'      },
        { q: 'Your contact number?',             ph: '10-digit mobile number',    type: 'tel'       },
        { q: 'What are your skills?',            ph: 'Choose all that apply',     type: 'skills'    },
        { q: 'Your interests?',                  ph: 'Pick your interests',       type: 'interests' },
        { q: 'Which state are you from?',        ph: 'Select your state',         type: 'location'  },
        { q: 'Are you looking for work?',        ph: 'Select your role',          type: 'role'      },
        { q: 'Upload your Aadhaar card',         ph: 'JPG / PNG, max 5 MB',      type: 'file'      },
      ],
    },
  },
  hi: {
    toggle: 'English',
    nav: {
      home: 'होम', services: 'सेवाएं', pickDrop: 'पिक & ड्रॉप',
      manpower: 'मैनपावर', gigs: 'नौकरी खोजें', workers: 'वर्कर्स',
      joinWorker: 'वर्कर बनें', postJob: 'नौकरी पोस्ट करें',
      profile: 'मेरी प्रोफ़ाइल', dashboard: 'डैशबोर्ड', logout: 'लॉग आउट', login: 'लॉगिन',
    },
    home: {
      badge: 'भारत का सबसे बड़ा लेबर मार्केटप्लेस',
      h1a: 'सत्यापित वर्कर्स किराए पर लें।',
      h1b: 'नौकरी खोजें। टीम बनाएं।',
      sub: 'एक सफाई कर्मचारी से लेकर 50 लोगों की कंस्ट्रक्शन टीम तक — किसी भी जरूरत के लिए कुशल, बैकग्राउंड-सत्यापित वर्कर्स बुक करें।',
      hireBtn: 'वर्कर किराए पर लें →',
      manpowerBtn: 'मैनपावर टीम बुक करें',
      jobBtn: 'नौकरी खोजें',
      searchPh: 'वर्कर, सेवाएं या नौकरी खोजें...',
      categoriesTitle: 'सभी सेवा श्रेणियां',
      categoriesSub: '8 मुख्य श्रेणियां · 48 उप-सेवाएं · 48,000+ सत्यापित वर्कर्स',
      viewAll: 'सभी देखें',
      pickDropTitle: '🛵 पिक & ड्रॉप रनर',
      pickDropSub: 'किराने का सामान, दवाइयां, पार्सल या किसी भी दुकान से कुछ भी — अपने पड़ोस में भेजें।',
      sendRunner: 'रनर भेजें →',
      workersTitle: 'टॉप रेटेड वर्कर्स',
      workersSub: 'व्यक्तिगत रूप से सत्यापित, कौशल-परीक्षित और बीमाकृत',
      browseAll: 'सभी देखें',
      trustTitle: 'विश्वास और सुरक्षा पर निर्मित',
      trustSub: 'UrbanServe पर हर वर्कर सत्यापित, परीक्षित और बीमाकृत है',
      manpowerCTATitle: 'पूरी लेबर टीम चाहिए?',
      manpowerCTASub: 'कंस्ट्रक्शन, इवेंट, फैक्ट्री और शिफ्टिंग के लिए 1 से 50+ वर्कर्स चुनें। 4 घंटे में टीम तैनात।',
      buildTeam: 'टीम बनाएं →',
      pricingTitle: 'पारदर्शी मूल्य निर्धारण',
      pricingSub: 'कोई छुपा शुल्क नहीं। सभी बुकिंग पर 12–18% प्लेटफ़ॉर्म शुल्क।',
      gigTitle: 'काम की तलाश में हैं?',
      gigSub: 'IT, कंस्ट्रक्शन, दुकानों, कार्यालयों और फैक्ट्रियों में पार्ट-टाइम, डेली वेज, कॉन्ट्रैक्ट नौकरियां खोजें।',
      browseJobs: 'सभी नौकरियां देखें →',
      registerWorker: 'वर्कर के रूप में रजिस्टर करें',
      aiTitle: 'AI-संचालित स्मार्ट मिलान',
      aiSub: 'हमारा AI इंजन आपकी जरूरतों के अनुसार तुरंत 3 सबसे उपयुक्त सत्यापित वर्कर्स से मिलाता है।',
      aiBtn: 'AI मिलान आज़माएं →',
    },
    gigs: {
      title: '💼 गिग जॉब मार्केटप्लेस',
      sub: 'डेली वेज, प्रति घंटा, पार्ट-टाइम, कॉन्ट्रैक्ट और फुल-टाइम अवसर',
      allCats: 'सभी श्रेणियां',
      allTypes: 'सभी प्रकार',
      apply: 'आवेदन →',
      urgent: '🔴 अत्यावश्यक',
      noJobs: 'इस फ़िल्टर से कोई नौकरी मेल नहीं खाती।',
      postBtn: 'नौकरी पोस्ट करें',
      postTitle: 'नई नौकरी रिक्ति पोस्ट करें',
      jobTitle: 'नौकरी का शीर्षक',
      company: 'कंपनी / नाम',
      jobType: 'नौकरी का प्रकार',
      pay: 'वेतन / भुगतान',
      location: 'स्थान / शहर',
      skills: 'आवश्यक कौशल (अल्पविराम से अलग)',
      category: 'श्रेणी',
      markUrgent: 'अत्यावश्यक के रूप में चिह्नित करें',
      postSubmit: 'नौकरी लाइव पोस्ट करें →',
      cancel: 'रद्द करें',
      workerCTATitle: 'क्या आप एक कुशल वर्कर हैं?',
      workerCTASub: 'UrbanServe पर 48,000+ सत्यापित वर्कर्स के साथ जुड़ें। डेली पेआउट, जॉब गारंटी और बीमा।',
      joinBtn: 'वर्कर के रूप में जुड़ें — निःशुल्क →',
      liveTag: '🟢 लाइव नौकरियां',
    },
    dashboard: {
      title: 'मेरा डैशबोर्ड',
      welcome: (n: string) => `नमस्ते, ${n} 👋`,
      subtitle: 'आपकी प्रोफ़ाइल एक नज़र में',
      editProfile: 'प्रोफ़ाइल संपादित करें',
      saveProfile: 'परिवर्तन सहेजें',
      cancel: 'रद्द करें',
      logout: 'लॉग आउट',
      labels: {
        name: 'पूरा नाम', email: 'ईमेल', dob: 'जन्म तिथि',
        contact: 'संपर्क', skills: 'कौशल', interests: 'रुचियाँ',
        location: 'स्थान', aadhaar: 'आधार कार्ड',
        verified: 'सत्यापित', member: 'सदस्य बने', role: 'खाता प्रकार',
      },
      noAadhaar: 'अपलोड नहीं हुआ',
      viewAadhaar: 'आधार देखें',
      myJobs: 'मेरे आवेदन',
      noApps: 'कोई आवेदन नहीं।',
      status: { pending: 'लंबित', accepted: 'स्वीकृत', rejected: 'अस्वीकृत' },
    },
    onboarding: {
      title: 'अपनी प्रोफ़ाइल सेट करें',
      sub: '2 मिनट लगते हैं। कभी भी संपादित कर सकते हैं।',
      step: (c: number, t: number) => `चरण ${c} / ${t}`,
      back: 'वापस', next: 'आगे', submit: 'जमा करें', saving: 'सहेज रहे हैं…',
      skip: 'अभी छोड़ें',
      qs: [
        { q: 'आपका पूरा नाम क्या है?',       ph: 'अपना पूरा नाम लिखें',       type: 'text'      },
        { q: 'आपकी जन्म तिथि?',              ph: 'जन्म तिथि चुनें',           type: 'date'      },
        { q: 'आपका संपर्क नंबर?',             ph: '10 अंकों का मोबाइल नंबर',  type: 'tel'       },
        { q: 'आपके कौशल क्या हैं?',           ph: 'सभी लागू विकल्प चुनें',    type: 'skills'    },
        { q: 'आपकी रुचियाँ?',                 ph: 'अपनी रुचियाँ चुनें',       type: 'interests' },
        { q: 'आप किस राज्य से हैं?',          ph: 'अपना राज्य चुनें',         type: 'location'  },
        { q: 'क्या आप काम की तलाश में हैं?',  ph: 'अपनी भूमिका चुनें',        type: 'role'      },
        { q: 'अपना आधार कार्ड अपलोड करें',   ph: 'JPG / PNG, 5MB तक',        type: 'file'      },
      ],
    },
  },
};

export const SKILLS_EN = ['Cooking','Farming','Carpentry','Tailoring','Driving','Teaching','Nursing','Plumbing','Electrical','IT/Computer','Painting','Masonry','Photography','Music','Welding'];
export const SKILLS_HI = ['खाना पकाना','खेती','बढ़ईगीरी','सिलाई','ड्राइविंग','शिक्षण','नर्सिंग','प्लंबिंग','इलेक्ट्रिकल','IT/कंप्यूटर','चित्रकारी','राजमिस्त्री','फोटोग्राफी','संगीत','वेल्डिंग'];
export const INTERESTS_EN = ['Sports','Travel','Reading','Music','Art','Cooking','Technology','Farming','Business','Social Work','Yoga','Cinema','Nature','Fitness'];
export const INTERESTS_HI = ['खेल','यात्रा','पढ़ना','संगीत','कला','खाना','तकनीक','खेती','व्यापार','सामाजिक कार्य','योग','सिनेमा','प्रकृति','फिटनेस'];
export const STATES = ['Andhra Pradesh','Arunachal Pradesh','Assam','Bihar','Chhattisgarh','Goa','Gujarat','Haryana','Himachal Pradesh','Jharkhand','Karnataka','Kerala','Madhya Pradesh','Maharashtra','Manipur','Meghalaya','Mizoram','Nagaland','Odisha','Punjab','Rajasthan','Sikkim','Tamil Nadu','Telangana','Tripura','Uttar Pradesh','Uttarakhand','West Bengal','Delhi','Jammu & Kashmir','Ladakh'];
